/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eroldme_jni_calculator_Calculator */

#ifndef _Included_com_eroldme_jni_calculator_Calculator
#define _Included_com_eroldme_jni_calculator_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eroldme_jni_calculator_Calculator
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_eroldme_jni_calculator_Calculator_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_eroldme_jni_calculator_Calculator
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_eroldme_jni_calculator_Calculator_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_eroldme_jni_calculator_Calculator
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_eroldme_jni_calculator_Calculator_divide
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_eroldme_jni_calculator_Calculator
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_eroldme_jni_calculator_Calculator_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
